In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import gmaps
from config import gkey
gmaps.configure(api_key=gkey)


file_path = '..\Resources\California_PPP.csv'

california_df=pd.read_csv(file_path)
california_df.shape

(1302241, 23)

In [2]:
#this code takes the county and city from cdtfa and cleans it removing special characters and ()


url ='https://www.cdtfa.ca.gov/taxes-and-fees/rates.aspx'

california_counties_pull = pd.read_html(url, header=0)
california_counties = california_counties_pull[0]
california_counties = california_counties[['Location', 'County']]
california_counties['Location'] = california_counties['Location'].str.replace('*','', regex = False)
california_counties['Location'] = california_counties['Location'].str.replace(r"\(.*\)","")
california_counties['Location']  = california_counties['Location'].str.strip()
california_counties=california_counties.rename(columns={'Location': 'BorrowerCity'})
california_counties


#this cleans the city column to prepare for merge

california_df.columns

title_case = california_df['BorrowerCity'].str.title()
california_df['BorrowerCity'] = title_case
california_df['BorrowerCity'] = california_df['BorrowerCity'].replace(
    {'City Of Industry': 'City of Industry','Carmel':'Carmel-by-the-Sea', 'Carmel-By-The-Sea': 'Carmel-by-the-Sea',
    'Huntingtn Bch':'Huntington Beach','Rch Cucamonga':'Rancho Cucamonga','N Hollywood':'North Hollywood','La Canada Flintridge':'La Canada- Flintridge',
    'Woodland Hls':'Woodland Hills','La Canada':'La Canada- Flintridge','Playa Vista':'Los Angeles','Newport Coast':'Newport Beach'})

<ipython-input-2-bad1f6a47f09>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  california_counties['Location'] = california_counties['Location'].str.replace('*','', regex = False)
<ipython-input-2-bad1f6a47f09>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  california_counties['Location'] = california_counties['Location'].str.replace(r"\(.*\)","")
<ipython-input-2-bad1f6a47f09>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  california_counties['Location'] = california_counties['Location'].str.replace(r"\(.*\)","")
<ipython-input-2-bad1f6a47f09>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  california_counties['Location']  = california_counties['Location'].str.strip()

In [3]:
#this pulls in county lat lon, population data from https://data.ca.gov/dataset/b-6-comparison-by-county2/resource/02ec81f7-2d3c-446d-a1a0-1387647d2d15

file_path = '..\Resources\County_Data.csv'

county_df=pd.read_csv(file_path)
county_df=county_df.loc[county_df['Taxable Year']==2018]
county_df=county_df[['County','Population','AGI','Latitude','Longitude']]
county_df

           County  Population           AGI   Latitude   Longitude
41        Alameda   1662730.0  8.948891e+10  37.720226 -122.164352
75         Colusa     22260.0  6.626438e+08  39.167981 -122.299067
98          Glenn     28755.0  6.175000e+08  39.590287 -122.078097
103          Yolo    222054.0  6.988605e+09  38.683827 -121.912742
142   Santa Clara   1955946.0  1.535260e+11  37.234238 -121.731723
...           ...         ...           ...        ...         ...
1292       Tehama     64703.0  1.111567e+09  40.255064 -122.293772
1300       Madera    158511.0  2.860856e+09  37.096371 -119.890430
1319    Calaveras     44572.0  1.248550e+09  38.254627 -120.465738
1394       Solano    439975.0  1.420713e+10  38.176818 -122.035299
1395        Kings    153318.0  2.357833e+09  36.019471 -120.018164

[61 rows x 5 columns]

In [4]:
#this merges the county table from cdtfa with our ppp data set

california_df_merge = pd.merge(california_df, california_counties, on="BorrowerCity", how="left")

#this finds the rows that does not have counties, there are numerous miss spellings so we cleaned the data down to less than 1% of the total data set
pd.isna(california_df_merge['County']).sum()
df_no_county = california_df_merge.loc[california_df_merge['County'].isna()]
print(df_no_county["LoanNumber"].count())
df_bin = df_no_county.groupby("BorrowerCity")
df_bin.count().sort_values("LoanNumber", ascending=False).head(10)

12737

,LoanNumber,DateApproved,ProcessingMethod,BorrowerName,BorrowerAddress,BorrowerState,BorrowerZip,CurrentApprovalAmount,RuralUrbanIndicator,HubzoneIndicator,...,NAICSCode,Race,PAYROLL_PROCEED,BusinessType,OriginatingLender,OriginatingLenderCity,OriginatingLenderState,Gender,Veteran,County
BorrowerCity,,,,,,,,,,,,,,,,,,,,,
Mckinleyville,300,300,300,300,300,300,300,300,300,300,...,297,300,300,300,300,300,300,300,300,0
W Hollywood,279,279,279,279,279,279,279,279,279,279,...,268,279,279,279,279,279,279,279,279,0
Sn Bernrdno,259,259,259,259,259,259,259,259,259,259,...,248,259,259,259,259,259,259,259,259,0
Oak Hills,228,228,228,228,228,228,228,228,228,228,...,225,228,228,228,228,228,228,228,228,0
Westlake Vlg,226,226,226,226,226,226,226,226,226,226,...,216,226,226,226,226,226,226,226,226,0
S Lake Tahoe,218,218,218,218,218,218,218,218,218,218,...,195,218,218,218,218,218,218,218,218,0
Lake Balboa,216,216,216,216,216,216,216,216,216,216,...,208,216,216,216,216,216,216,216,216,0
S San Fran,214,214,214,214,214,214,214,214,214,214,...,212,214,214,214,214,214,214,214,214,0
Cardiff,212,212,212,212,212,212,212,212,212,212,...,200,212,211,212,212,212,212,212,212,0
Rncho Cordova,208,208,208,208,208,208,208,208,208,208,...,199,208,208,208,208,208,208,208,208,0

In [5]:
#This creates the county data by PPP and PPS
california_df_county = california_df_merge[['LoanNumber','CurrentApprovalAmount','County','ProcessingMethod']]

california_df_county_ppp = california_df_county.loc[california_df_county["ProcessingMethod"]=="PPP"]
california_df_county_pps = california_df_county.loc[california_df_county["ProcessingMethod"]=="PPS"]

In [6]:
#This is PPP county Data

county_group_ppp = california_df_county_ppp.groupby('County')
ppp_loan_count = county_group_ppp['CurrentApprovalAmount'].count()
ppp_loan_amount = county_group_ppp['CurrentApprovalAmount'].sum()/1000000

total_loan_count_ppp = ppp_loan_count.sum()
total_loan_sum_ppp = ppp_loan_amount.sum()


ppp_county = pd.merge(ppp_loan_count, ppp_loan_amount, on="County", how="left")
ppp_county=ppp_county.rename(columns={'CurrentApprovalAmount_x': 'Loan Count','CurrentApprovalAmount_y': 'Loan Amount (Millions)'})
ppp_county["Count %"] = ppp_county["Loan Count"]/total_loan_count_ppp
ppp_county["Amount %"] = ppp_county["Loan Amount (Millions)"]/total_loan_sum_ppp

ppp_county = pd.merge(ppp_county, county_df, on="County", how="left")
ppp_county["AGI"]=ppp_county["AGI"]/1000000
ppp_county=ppp_county.rename(columns={'AGI': 'AGI (Millions)'})
ppp_county["Amount Per Person"]=(ppp_county["Loan Amount (Millions)"]*1000000)/ppp_county["Population"]

ppp_county.sort_values("Loan Amount (Millions)", ascending=False)

,County,Loan Count,Loan Amount (Millions),Count %,Amount %,Population,AGI (Millions),Latitude,Longitude,Amount Per Person
18,Los Angeles,323117,21474.230487,0.343104,0.287401,10269935.0,331343.000000,34.059483,-118.242048,2090.980175
29,Orange,87502,8343.040584,0.092915,0.111659,3215372.0,139542.000000,33.660734,-117.936137,2594.735721
36,San Diego,74351,6435.608582,0.078950,0.086131,3344438.0,118521.000000,32.789640,-117.193658,1924.272055
0,Alameda,41089,4056.945323,0.043631,0.054296,1662730.0,89488.907459,37.720226,-122.164352,2439.930309
42,Santa Clara,36750,4015.774333,0.039023,0.053745,1955946.0,153526.000000,37.234238,-121.731723,2053.111043
37,San Francisco,30035,3404.610667,0.031893,0.045566,886618.0,81884.509966,37.757700,-122.437600,3839.997233
32,Riverside,44785,2812.927343,0.047555,0.037647,2420714.0,56781.365151,33.777574,-115.470693,1162.023825
35,San Bernardino,44993,2692.858845,0.047776,0.036040,2178940.0,49104.644374,34.522586,-115.537257,1235.857272
33,Sacramento,32120,2190.670012,0.034107,0.029319,1537386.0,44179.011186,38.192378,-121.602064,1424.931677
6,Contra Costa,25139,1901.416342,0.026694,0.025448,1147327.0,56590.780658,37.988180,-121.937140,1657.257558
40,San Mateo,17190,1848.249913,0.018253,0.024736,774570.0,76789.387694,37.439441,-122.334460,2386.162533
55,Ventura,18729,1582.827250,0.019888,0.021184,855713.0,32973.598624,34.277091,-119.217850,1849.717428
9,Fresno,17447,1454.131225,0.018526,0.019461,1010837.0,22003.081162,36.812760,-119.682694,1438.541748
48,Sonoma,12157,1130.369301,0.012909,0.015128,500499.0,20032.919687,38.493672,-122.930263,2258.484634
14,Kern,12652,995.856128,0.013435,0.013328,907055.0,18304.520126,35.376768,-118.807357,1097.900489
38,San Joaquin,12759,907.962267,0.013548,0.012152,760310.0,16746.479329,37.933703,-121.344401,1194.200085
41,Santa Barbara,9961,901.517006,0.010577,0.012065,452953.0,15860.257408,34.421191,-119.698820,1990.310267
20,Marin,9675,828.826431,0.010273,0.011093,262326.0,25997.689202,38.039526,-122.729951,3159.528340
30,Placer,9180,783.642035,0.009748,0.010488,389278.0,17472.803059,39.031621,-120.883066,2013.065302
49,Stanislaus,8193,722.786242,0.008700,0.009673,554616.0,12962.858121,37.501488,-121.216480,1303.219240
26,Monterey,6376,696.051282,0.006770,0.009316,444252.0,12887.545034,36.324707,-121.296836,1566.793806
53,Tulare,5507,524.042844,0.005848,0.007014,475781.0,8237.584622,36.282543,-118.265210,1101.437099
39,San Luis Obispo,6645,521.577577,0.007056,0.006981,279321.0,9712.873483,35.274350,-120.612497,1867.305277
43,Santa Cruz,5870,513.982676,0.006233,0.006879,275168.0,11490.106643,37.021598,-121.947130,1867.886804
47,Solano,7720,511.750739,0.008198,0.006849,439975.0,14207.125522,38.176818,-122.035299,1163.135948
27,Napa,3596,434.060353,0.003818,0.005809,140573.0,6493.370481,38.459382,-122.332856,3087.793197
56,Yolo,3424,317.577754,0.003636,0.004250,222054.0,6988.604663,38.683827,-121.912742,1430.182539
44,Shasta,3293,288.940305,0.003497,0.003867,178239.0,4472.880588,40.535022,-122.502164,1621.083516
3,Butte,3467,285.393648,0.003681,0.003820,227353.0,5182.918695,39.591273,-121.672882,1255.288682
8,El Dorado,3423,267.742033,0.003635,0.003583,189360.0,8250.430479,38.763942,-120.606059,1413.931309
23,Merced,3105,236.079955,0.003297,0.003160,279433.0,4751.540930,37.132424,-120.716752,844.853524
11,Humboldt,2062,167.125834,0.002190,0.002237,135765.0,2909.751925,40.861485,-123.858512,1230.993507
19,Madera,1790,154.181648,0.001901,0.002063,158511.0,2860.856134,37.096371,-119.890430,972.687373
28,Nevada,2441,152.589092,0.002592,0.002042,98626.0,3316.127622,39.295489,-120.900873,1547.148747
12,Imperial,1701,147.108158,0.001806,0.001969,188948.0,3125.218054,33.077294,-114.751536,778.564253
50,Sutter,1823,136.652409,0.001936,0.001829,101337.0,2202.274623,39.011311,-121.723334,1348.494711
22,Mendocino,1583,122.379580,0.001681,0.001638,88875.0,2030.657991,39.310341,-123.651778,1376.985433
15,Kings,1403,119.764408,0.001490,0.001603,153318.0,2357.833005,36.019471,-120.018164,781.150340
34,San Benito,852,80.209172,0.000905,0.001073,61437.0,2114.072012,36.500249,-121.091510,1305.551570
51,Tehama,685,58.607197,0.000727,0.000784,64703.0,1111.567446,40.255064,-122.293772,905.787942
54,Tuolumne,880,55.929086,0.000934,0.000749,52843.0,1387.295550,37.963860,-119.892073,1058.401028
5,Colusa,378,53.005302,0.000401,0.000709,22260.0,662.643834,39.167981,-122.299067,2381.190571
57,Yuba,668,48.806976,0.000709,0.000653,77426.0,1415.396319,39.271295,-121.379356,630.369338
16,Lake,674,47.101414,0.000716,0.000630,65020.0,1200.985491,39.065005,-122.657019,724.414234
10,Glenn,447,46.453265,0.000475,0.000622,28755.0,617.500029,39.590287,-122.078097,1615.484780
46,Siskiyou,765,38.612543,0.000812,0.000517,44128.0,866.019924,41.402454,-123.175012,875.012307
4,Calaveras,700,35.837507,0.000743,0.000480,44572.0,1248.550447,38.254627,-120.465738,804.036317
13,Inyo,302,30.821792,0.000321,0.000413,18522.0,506.657172,36.633503,-118.255959,1664.063930
25,Mono,410,27.470828,0.000435,0.000368,13827.0,341.407669,38.347100,-119.332727,1986.752588
2,Amador,529,27.162579,0.000562,0.000364,38146.0,1031.896983,38.472162,-120.574195,712.068870
31,Plumas,363,26.688864,0.000385,0.000357,18702.0,437.104184,40.005107,-121.007746,1427.059376
17,Lassen,272,17.427341,0.000289,0.000233,30527.0,544.777716,40.432559,-120.649559,570.882854
7,Del Norte,276,17.393756,0.000293,0.000233,27419.0,450.228880,41.705570,-123.892004,634.368738
21,Mariposa,182,10.070317,0.000193,0.000135,17904.0,356.266504,37.722893,-119.976736,562.461853
24,Modoc,148,6.928534,0.000157,0.000093,9487.0,122.687945,41.713682,-120.943072,730.318706
52,Trinity,99,5.811949,0.000105,0.000078,13385.0,195.093155,40.840929,-122.972844,434.213581
1,Alpine,20,1.844885,0.000021,0.000025,1134.0,27.576337,38.588429,-119.712442,1626.883086
45,Sierra,44,1.226871,0.000047,0.000016,3136.0,64.056324,39.563161,-120.773951,391.221591

In [7]:
locations = ppp_county[["Latitude", "Longitude"]].astype(float)
loan_amount = ppp_county["Loan Amount (Millions)"].astype(float)

fig = gmaps.figure()

heat_layer = gmaps.heatmap_layer(locations, weights=loan_amount, dissipating=False, max_intensity=100, point_radius = 1)

fig.add_layer(heat_layer)

fig

Figure(layout=FigureLayout(height='420px'))

In [128]:
#This is PPS county Data

county_group_pps = california_df_county_pps.groupby('County')
pps_loan_count = county_group_pps['CurrentApprovalAmount'].count()
pps_loan_amount = county_group_pps['CurrentApprovalAmount'].sum()/1000000

total_loan_count_pps = pps_loan_count.sum()
total_loan_sum_pps = pps_loan_amount.sum()


pps_county = pd.merge(pps_loan_count, pps_loan_amount, on="County", how="left")
pps_county=pps_county.rename(columns={'CurrentApprovalAmount_x': 'Loan Count','CurrentApprovalAmount_y': 'Loan Amount (Millions)'})
pps_county["Count %"] = pps_county["Loan Count"]/total_loan_count_pps
pps_county["Amount %"] = pps_county["Loan Amount (Millions)"]/total_loan_sum_pps

pps_county = pd.merge(pps_county, county_df, on="County", how="left")
pps_county["AGI"]=pps_county["AGI"]/1000000
pps_county=pps_county.rename(columns={'AGI': 'AGI (Millions)'})
pps_county["Amount Per Person"]=(pps_county["Loan Amount (Millions)"]*1000000)/pps_county["Population"]

pps_county.sort_values("Loan Amount (Millions)", ascending=False)

,County,Loan Count,Loan Amount (Millions),Count %,Amount %,Population,AGI (Millions),Latitude,Longitude,Amount Per Person
18,Los Angeles,123793,8903.289006,0.349080,0.308090,10269935.0,331343.000000,34.059483,-118.242048,866.927493
29,Orange,36278,3266.553838,0.102299,0.113036,3215372.0,139542.000000,33.660734,-117.936137,1015.917859
36,San Diego,28960,2512.439561,0.081663,0.086941,3344438.0,118521.000000,32.789640,-117.193658,751.229223
42,Santa Clara,15903,1561.953556,0.044844,0.054050,1955946.0,153526.000000,37.234238,-121.731723,798.566809
0,Alameda,16590,1526.182044,0.046782,0.052812,1662730.0,89488.907459,37.720226,-122.164352,917.877253
37,San Francisco,13291,1403.370639,0.037479,0.048562,886618.0,81884.509966,37.757700,-122.437600,1582.835718
32,Riverside,14600,1049.402431,0.041170,0.036314,2420714.0,56781.365151,33.777574,-115.470693,433.509465
35,San Bernardino,13724,913.583043,0.038700,0.031614,2178940.0,49104.644374,34.522586,-115.537257,419.278660
40,San Mateo,7532,770.520095,0.021239,0.026663,774570.0,76789.387694,37.439441,-122.334460,994.771415
33,Sacramento,10328,731.838471,0.029124,0.025325,1537386.0,44179.011186,38.192378,-121.602064,476.027797
6,Contra Costa,9539,720.919394,0.026899,0.024947,1147327.0,56590.780658,37.988180,-121.937140,628.346926
55,Ventura,7427,609.794090,0.020943,0.021101,855713.0,32973.598624,34.277091,-119.217850,712.615199
9,Fresno,5285,441.237037,0.014903,0.015269,1010837.0,22003.081162,36.812760,-119.682694,436.506615
48,Sonoma,4609,426.010278,0.012997,0.014742,500499.0,20032.919687,38.493672,-122.930263,851.171088
14,Kern,3912,380.305095,0.011031,0.013160,907055.0,18304.520126,35.376768,-118.807357,419.274570
41,Santa Barbara,4157,373.671801,0.011722,0.012931,452953.0,15860.257408,34.421191,-119.698820,824.968156
20,Marin,4209,357.592512,0.011869,0.012374,262326.0,25997.689202,38.039526,-122.729951,1363.160768
38,San Joaquin,3708,289.547625,0.010456,0.010020,760310.0,16746.479329,37.933703,-121.344401,380.828379
30,Placer,3265,264.920572,0.009207,0.009167,389278.0,17472.803059,39.031621,-120.883066,680.543396
26,Monterey,2473,251.554156,0.006974,0.008705,444252.0,12887.545034,36.324707,-121.296836,566.242034
49,Stanislaus,2515,224.058703,0.007092,0.007753,554616.0,12962.858121,37.501488,-121.216480,403.988892
39,San Luis Obispo,2515,214.818362,0.007092,0.007434,279321.0,9712.873483,35.274350,-120.612497,769.073438
43,Santa Cruz,2278,213.033627,0.006424,0.007372,275168.0,11490.106643,37.021598,-121.947130,774.194771
47,Solano,2372,187.179497,0.006689,0.006477,439975.0,14207.125522,38.176818,-122.035299,425.432120
27,Napa,1495,183.633269,0.004216,0.006354,140573.0,6493.370481,38.459382,-122.332856,1306.319630
53,Tulare,1473,125.394616,0.004154,0.004339,475781.0,8237.584622,36.282543,-118.265210,263.555325
56,Yolo,1286,112.936591,0.003626,0.003908,222054.0,6988.604663,38.683827,-121.912742,508.599671
44,Shasta,1071,94.447497,0.003020,0.003268,178239.0,4472.880588,40.535022,-122.502164,529.892430
8,El Dorado,1175,92.411497,0.003313,0.003198,189360.0,8250.430479,38.763942,-120.606059,488.020155
3,Butte,1123,91.322218,0.003167,0.003160,227353.0,5182.918695,39.591273,-121.672882,401.675888
23,Merced,862,65.234036,0.002431,0.002257,279433.0,4751.540930,37.132424,-120.716752,233.451439
11,Humboldt,738,58.770850,0.002081,0.002034,135765.0,2909.751925,40.861485,-123.858512,432.886605
28,Nevada,822,53.851586,0.002318,0.001863,98626.0,3316.127622,39.295489,-120.900873,546.018144
12,Imperial,600,51.875150,0.001692,0.001795,188948.0,3125.218054,33.077294,-114.751536,274.547229
19,Madera,559,46.017361,0.001576,0.001592,158511.0,2860.856134,37.096371,-119.890430,290.310203
50,Sutter,572,45.210800,0.001613,0.001564,101337.0,2202.274623,39.011311,-121.723334,446.143072
22,Mendocino,502,38.055909,0.001416,0.001317,88875.0,2030.657991,39.310341,-123.651778,428.195882
34,San Benito,318,31.695125,0.000897,0.001097,61437.0,2114.072012,36.500249,-121.091510,515.896362
15,Kings,363,30.395203,0.001024,0.001052,153318.0,2357.833005,36.019471,-120.018164,198.249408
54,Tuolumne,254,19.661745,0.000716,0.000680,52843.0,1387.295550,37.963860,-119.892073,372.078508
16,Lake,198,16.885643,0.000558,0.000584,65020.0,1200.985491,39.065005,-122.657019,259.699217
25,Mono,192,16.240768,0.000541,0.000562,13827.0,341.407669,38.347100,-119.332727,1174.569165
10,Glenn,101,14.173258,0.000285,0.000490,28755.0,617.500029,39.590287,-122.078097,492.897153
5,Colusa,104,13.148735,0.000293,0.000455,22260.0,662.643834,39.167981,-122.299067,590.688925
51,Tehama,192,13.129326,0.000541,0.000454,64703.0,1111.567446,40.255064,-122.293772,202.916806
57,Yuba,196,12.781043,0.000553,0.000442,77426.0,1415.396319,39.271295,-121.379356,165.074309
4,Calaveras,221,12.162319,0.000623,0.000421,44572.0,1248.550447,38.254627,-120.465738,272.869039
46,Siskiyou,205,10.348796,0.000578,0.000358,44128.0,866.019924,41.402454,-123.175012,234.517677
13,Inyo,109,8.984233,0.000307,0.000311,18522.0,506.657172,36.633503,-118.255959,485.057364
2,Amador,167,8.674666,0.000471,0.000300,38146.0,1031.896983,38.472162,-120.574195,227.406972
31,Plumas,140,8.156187,0.000395,0.000282,18702.0,437.104184,40.005107,-121.007746,436.113064
7,Del Norte,95,7.976201,0.000268,0.000276,27419.0,450.228880,41.705570,-123.892004,290.900518
21,Mariposa,79,7.675410,0.000223,0.000266,17904.0,356.266504,37.722893,-119.976736,428.698039
17,Lassen,75,7.243489,0.000211,0.000251,30527.0,544.777716,40.432559,-120.649559,237.281404
1,Alpine,6,2.288630,0.000017,0.000079,1134.0,27.576337,38.588429,-119.712442,2018.192240
52,Trinity,26,1.641845,0.000073,0.000057,13385.0,195.093155,40.840929,-122.972844,122.663056
24,Modoc,30,1.312901,0.000085,0.000045,9487.0,122.687945,41.713682,-120.943072,138.389521
45,Sierra,14,0.831458,0.000039,0.000029,3136.0,64.056324,39.563161,-120.773951,265.133320